from project.judge.models import *
from django.contrib.auth.models import User

user = User(username='user 1')
user.save()
user = User(username='user 2')
user.save()

institution = Institution(name='universitario')
institution.save()
institution = Institution(name='club')
institution.save()
institution = Institution(name='colegial')
institution.save()
institution = Institution(name='independiente')
institution.save()

gender = Gender(name='all girl')
gender.save()
gender = Gender(name='coed')
gender.save()
gender = Gender(name='all male')
gender.save()
gender = Gender(name='girl')
gender.save()
gender = Gender(name='male')
gender.save()

level = Level(name='1')
level.save()
level = Level(name='2')
level.save()
level = Level(name='3')
level.save()
level = Level(name='4')
level.save()
level = Level(name='5')
level.save()
level = Level(name='6')
level.save()
level = Level(name='4.2')
level.save()

division = Division(name='baby junior')
division.save()
division = Division(name='mini junior')
division.save()
division = Division(name='junior')
division.save()
division = Division(name='senior')
division.save()
division = Division(name='open')
division.save()
division = Division(name='individual')
division.save()

category = Category(name='flyer')
category.save()
category = Category(name='jumper')
category.save()
category = Category(name='tumbler')
category.save()
category = Category(name='parejas')
category.save()
category = Category(name='trio')
category.save()
category = Category(name='cuarteto')
category.save()
category = Category(name='equipo')
category.save()

round = Round(name='1')
round.save()
round = Round(name='2')
round.save()
round = Round(name='3')
round.save()

scoresheettype = ScoreSheetType(name='varsity')
scoresheettype.save()
scoresheettype = ScoreSheetType(name='nca')
scoresheettype.save()
scoresheettype = ScoreSheetType(name='uca')
scoresheettype.save()

scoremetric = ScoreMetric(name='difficulty')
scoremetric.save()
scoremetric = ScoreMetric(name='technique')
scoremetric.save()
scoremetric = ScoreMetric(name='creativity')
scoremetric.save()

locationtype = LocationType(name='pais')
locationtype.save()
locationtype = LocationType(name='departamento')
locationtype.save()
locationtype = LocationType(name='ciudad')
locationtype.save()
locationtype = LocationType(name='municipio')
locationtype.save()

status = Status(name='on time')
status.save()
status = Status(name='delayed')
status.save()
status = Status(name='checked')
status.save()

parentscorecategory = ParentScoreCategory(name='building skills')
parentscorecategory.save()
parentscorecategory = ParentScoreCategory(name='tumbling skills')
parentscorecategory.save()
parentscorecategory = ParentScoreCategory(name='overall routine')
parentscorecategory.save()

divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(name='1'), division=Division.objects.get(name='baby junior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(name='1'), division=Division.objects.get(name='mini junior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(name='2'), division=Division.objects.get(name='mini junior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='all girl'), level=Level.objects.get(name='2'), division=Division.objects.get(name='junior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='all girl'), level=Level.objects.get(name='3'), division=Division.objects.get(name='junior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(name='2'), division=Division.objects.get(name='senior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(name='3'), division=Division.objects.get(name='senior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(name='4'), division=Division.objects.get(name='senior'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='colegial'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='all girl'), level=Level.objects.get(name='2'), division=Division.objects.get(name='open'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='club'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='all girl'), level=Level.objects.get(name='3'), division=Division.objects.get(name='open'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='club'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='all girl'), level=Level.objects.get(name='4'), division=Division.objects.get(name='open'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='club'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(pk='4'), division=Division.objects.get(name='open'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='club'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(pk='5'), division=Division.objects.get(name='open'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='club'))
divisiongroup.save()
divisiongroup = DivisionGroup(gender=Gender.objects.get(name='coed'), level=Level.objects.get(pk='6'), division=Division.objects.get(name='open'), category=Category.objects.get(name='equipo'), institution=Institution.objects.get(name='club'))
divisiongroup.save()

scorecategory = ScoreCategory(name='stunts', parentscorecategory=ParentScoreCategory.objects.get(name='building skills'))
scorecategory.save()
scorecategory = ScoreCategory(name='pyramids', parentscorecategory=ParentScoreCategory.objects.get(name='building skills'))
scorecategory.save()
scorecategory = ScoreCategory(name='tosses', parentscorecategory=ParentScoreCategory.objects.get(name='building skills'))
scorecategory.save()
scorecategory = ScoreCategory(name='quantity/coed', parentscorecategory=ParentScoreCategory.objects.get(name='building skills'))
scorecategory.save()
scorecategory = ScoreCategory(name='standing tumbling', parentscorecategory=ParentScoreCategory.objects.get(name='tumbling skills'))
scorecategory.save()
scorecategory = ScoreCategory(name='running tumbling', parentscorecategory=ParentScoreCategory.objects.get(name='tumbling skills'))
scorecategory.save()
scorecategory = ScoreCategory(name='jumps', parentscorecategory=ParentScoreCategory.objects.get(name='tumbling skills'))
scorecategory.save()
scorecategory = ScoreCategory(name='routine composition', parentscorecategory=ParentScoreCategory.objects.get(name='overall routine'))
scorecategory.save()
scorecategory = ScoreCategory(name='performance', parentscorecategory=ParentScoreCategory.objects.get(name='overall routine'))
scorecategory.save()
scorecategory = ScoreCategory(name='dance', parentscorecategory=ParentScoreCategory.objects.get(name='overall routine'))
scorecategory.save()

location = Location(name='Guatemala', locationtype=LocationType.objects.get(name='pais'))
location.save()
location = Location(name='Guatemala', locationtype=LocationType.objects.get(name='departamento'), location=Location.objects.get(pk=1))
location.save()
location = Location(name='Guatemala', locationtype=LocationType.objects.get(name='ciudad'), location=Location.objects.get(pk=2))
location.save()
location = Location(name='Guatemala', locationtype=LocationType.objects.get(name='municipio'), location=Location.objects.get(pk=3))
location.save()

scoresheet = ScoreSheet(name='hoja de calificacion 1', scoresheettype=ScoreSheetType.objects.get(name='varsity'))
scoresheet.save()
scoresheet = ScoreSheet(name='hoja de calificacion 2', scoresheettype=ScoreSheetType.objects.get(name='varsity'))
scoresheet.save()
scoresheet = ScoreSheet(name='hoja de calificacion 3', scoresheettype=ScoreSheetType.objects.get(name='varsity'))
scoresheet.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='stunts'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='technique'), scorecategory=ScoreCategory.objects.get(name='stunts'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=2.5, scoremetric=ScoreMetric.objects.get(name='creativity'), scorecategory=ScoreCategory.objects.get(name='stunts'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='pyramids'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='technique'), scorecategory=ScoreCategory.objects.get(name='pyramids'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=2.5, scoremetric=ScoreMetric.objects.get(name='creativity'), scorecategory=ScoreCategory.objects.get(name='pyramids'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='tosses'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='technique'), scorecategory=ScoreCategory.objects.get(name='tosses'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='quantity/coed'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='standing tumbling'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='technique'), scorecategory=ScoreCategory.objects.get(name='standing tumbling'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='running tumbling'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='technique'), scorecategory=ScoreCategory.objects.get(name='running tumbling'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='jumps'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()
scoresheetelement = ScoreSheetElement(min_score=1, max_score=5, scoremetric=ScoreMetric.objects.get(name='technique'), scorecategory=ScoreCategory.objects.get(name='jumps'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=10, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='routine composition'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=10, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='performance'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

scoresheetelement = ScoreSheetElement(min_score=1, max_score=10, scoremetric=ScoreMetric.objects.get(name='difficulty'), scorecategory=ScoreCategory.objects.get(name='dance'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
scoresheetelement.save()

team = Team(name='butterfly', location=Location.objects.get(pk=4))
team.save()
team = Team(name='cheer force usac', location=Location.objects.get(pk=4))
team.save()
team = Team(name='cougars', location=Location.objects.get(pk=4))
team.save()
team = Team(name='cougars dinasty supreme', location=Location.objects.get(pk=4))
team.save()
team = Team(name='cougars magic dolls', location=Location.objects.get(pk=4))
team.save()
team = Team(name='eagles', location=Location.objects.get(pk=4))
team.save()
team = Team(name='evolution', location=Location.objects.get(pk=4))
team.save()
team = Team(name='fenix', location=Location.objects.get(pk=4))
team.save()
team = Team(name='golden digef', location=Location.objects.get(pk=4))
team.save()
team = Team(name='halcones de santa rosa', location=Location.objects.get(pk=4))
team.save()
team = Team(name='independiente', location=Location.objects.get(pk=4))
team.save()
team = Team(name='infinity', location=Location.objects.get(pk=4))
team.save()
team = Team(name='infinity all girl', location=Location.objects.get(pk=4))
team.save()
team = Team(name='infinity coed', location=Location.objects.get(pk=4))
team.save()
team = Team(name='landivar', location=Location.objects.get(pk=4))
team.save()
team = Team(name='lions', location=Location.objects.get(pk=4))
team.save()
team = Team(name='lions psj', location=Location.objects.get(pk=4))
team.save()
team = Team(name='little cougars', location=Location.objects.get(pk=4))
team.save()
team = Team(name='panthers', location=Location.objects.get(pk=4))
team.save()
team = Team(name='pegasos all stars', location=Location.objects.get(pk=4))
team.save()
team = Team(name='pegasos diamonds', location=Location.objects.get(pk=4))
team.save()
team = Team(name='pegasos legacy', location=Location.objects.get(pk=4))
team.save()
team = Team(name='pegasos shiny wings', location=Location.objects.get(pk=4))
team.save()
team = Team(name='phantoms', location=Location.objects.get(pk=4))
team.save()
team = Team(name='phantoms elite', location=Location.objects.get(pk=4))
team.save()
team = Team(name='phantoms midnight', location=Location.objects.get(pk=4))
team.save()
team = Team(name='queen', location=Location.objects.get(pk=4))
team.save()
team = Team(name='sabertooth', location=Location.objects.get(pk=4))
team.save()
team = Team(name='slifers', location=Location.objects.get(pk=4))
team.save()
team = Team(name='stars', location=Location.objects.get(pk=4))
team.save()
team = Team(name='suizo americano', location=Location.objects.get(pk=4))
team.save()
team = Team(name='tigers', location=Location.objects.get(pk=4))
team.save()
team = Team(name='titans', location=Location.objects.get(pk=4))
team.save()
team = Team(name='fenix 2', location=Location.objects.get(pk=4))
team.save()
team = Team(name='fenix 3', location=Location.objects.get(pk=4))
team.save()
team = Team(name='lions2 psj', location=Location.objects.get(pk=4))
team.save()
team = Team(name='lions3 psj', location=Location.objects.get(pk=4))
team.save()
team = Team(name='lions psj all male', location=Location.objects.get(pk=4))
team.save()
team = Team(name='panthers 2', location=Location.objects.get(pk=4))
team.save()
team = Team(name='infinity 2', location=Location.objects.get(pk=4))
team.save()
team = Team(name='infinity 3', location=Location.objects.get(pk=4))
team.save()
team = Team(name='stars 2', location=Location.objects.get(pk=4))
team.save()
team = Team(name='stars 3', location=Location.objects.get(pk=4))
team.save()
team = Team(name='stars 4', location=Location.objects.get(pk=4))
team.save()
team = Team(name='stars 5', location=Location.objects.get(pk=4))
team.save()
team = Team(name='phantoms 2', location=Location.objects.get(pk=4))
team.save()
team = Team(name='cougars 2', location=Location.objects.get(pk=4))
team.save()
team = Team(name='cheer force usac 2', location=Location.objects.get(pk=4))
team.save()
team = Team(name='independiente 2', location=Location.objects.get(pk=4))
team.save()

championship = Championship(name='anap', date=timezone.now(), address='guatemala')
championship.save()

championshipscoresheet = ChampionshipScoreSheet(championship=Championship.objects.get(name='anap'), scoresheet=ScoreSheet.objects.get(name='hoja de calificacion 1'))
championshipscoresheet.save()

registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='pegasos shiny wings'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=1), order=1)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='little cougars'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=2), order=2)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='titans'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=3), order=4)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='suizo americano'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=3), order=3)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='butterfly'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=4), order=5)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='pegasos legacy'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=4), order=6)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='infinity all girl'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=4), order=7)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='slifers'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=5), order=9)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='sabertooth'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=5), order=8)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='halcones de santa rosa'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=5), order=10)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='golden digef'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=5), order=11)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='fenix'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=5), order=12)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='lions psj'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=5), order=13)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='cougars magic dolls'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=6), order=16)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='pegasos diamonds'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=6), order=14)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='phantoms midnight'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=6), order=15)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='stars'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=7), order=21)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='landivar'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=7), order=23)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='evolution'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=7), order=20)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='lions'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=7), order=22)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='infinity coed'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=8), order=19)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='pegasos all stars'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=8), order=17)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='panthers'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=8), order=18)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='cougars dinasty supreme'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=9), order=25)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='phantoms elite'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=9), order=26)
registration.save()
registration = Registration(date=timezone.now(), total_men=10, total_women=10, coach='entrenador', team=Team.objects.get(name='cheer force usac'), championshipscoresheet=ChampionshipScoreSheet.objects.get(pk=1), divisiongroup=DivisionGroup.objects.get(pk=9), order=24)
registration.save()

userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=1), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=2), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=3), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=4), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=5), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=6), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=7), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=8), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=9), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=10), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=11), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=12), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=13), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=14), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=15), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=16), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=17), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=18), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=19), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=20), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=21), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=22), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=23), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=24), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=25), user=User.objects.get(username='user 1'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=26), user=User.objects.get(username='user 1'))
userregistrationround.save()

userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=1), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=2), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=3), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=4), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=5), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=6), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=7), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=8), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=9), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=10), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=11), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=12), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=13), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=14), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=15), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=16), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=17), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=18), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=19), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=20), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=21), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=22), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=23), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=24), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=25), user=User.objects.get(username='user 2'))
userregistrationround.save()
userregistrationround = UserRegistrationRound(status=Status.objects.get(name='on time'), round=Round.objects.get(name='1'), registration=Registration.objects.get(pk=26), user=User.objects.get(username='user 2'))
userregistrationround.save()

userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userskillpermission.save()

userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userskillpermission.save()

userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=3), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userskillpermission.save()

userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userskillpermission.save()

userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userskillpermission.save()

userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userskillpermission.save()
userskillpermission = UserSkillPermission(userregistrationround=UserRegistrationRound.objects.get(pk=29), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userskillpermission.save()

userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=1), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userscoresheetelement.save()

userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=2), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userscoresheetelement.save()

userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=2, userregistrationround=UserRegistrationRound.objects.get(pk=27), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userscoresheetelement.save()

userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=1))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=2))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=3))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=4))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=5))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=6))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=7))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=8))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=9))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=10))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=11))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=12))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=13))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=14))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=15))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=16))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=17))
userscoresheetelement.save()
userscoresheetelement = UserScoreSheetElement(value=4, userregistrationround=UserRegistrationRound.objects.get(pk=28), scoresheetelement=ScoreSheetElement.objects.get(pk=18))
userscoresheetelement.save()

UserRegistrationRound.objects.filter(pk=1).update(status=Status.objects.get(name="checked"))
UserRegistrationRound.objects.filter(pk=2).update(status=Status.objects.get(name="delayed"))

UserRegistrationRound.objects.filter(pk=27).update(status=Status.objects.get(name="checked"))
UserRegistrationRound.objects.filter(pk=28).update(status=Status.objects.get(name="delayed"))
